CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`joinclassinstructor` AS select `I`.`instructorID` AS `instructorID`,`I`.`name` AS `InstructorName`,`I`.`surname` AS `InstructorSurname`,`CO`.`courseID` AS `courseID`,`CO`.`name` AS `CourseName`,`CL`.`classID` AS `classID`,`IGC`.`sectionID` AS `sectionID`,`CL`.`year` AS `year`,`CL`.`term` AS `term` from (((`471db`.`instructor` `I` join `471db`.`course` `CO`) join `471db`.`class` `CL`) join `471db`.`instructorgivescourse` `IGC`) where ((`I`.`instructorID` = `IGC`.`instructorID`) and (`IGC`.`classID` = `CL`.`classID`) and (`CO`.`courseID` = `CL`.`courseID`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`joincourseclasssection` AS select `CO`.`courseID` AS `courseID`,`CO`.`name` AS `CourseName`,`CO`.`credit` AS `credit`,`CL`.`classID` AS `classID`,`CL`.`year` AS `year`,`CL`.`term` AS `term`,`S`.`sectionID` AS `sectionID`,`S`.`quota` AS `quota`,`S`.`location` AS `SectionLocation`,`S`.`day1` AS `day1`,`S`.`startTime1` AS `startTime1`,`S`.`endTime1` AS `endTime1`,`S`.`day2` AS `day2`,`S`.`startTime2` AS `startTime2`,`S`.`endTime2` AS `endTime2`,`S`.`day3` AS `day3`,`S`.`startTime3` AS `startTime3`,`S`.`endTime3` AS `endTime3` from ((`471db`.`course` `CO` join `471db`.`class` `CL`) join `471db`.`section` `S`) where ((`CO`.`courseID` = `CL`.`courseID`) and (`S`.`classID` = `CL`.`classID`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`joininstructordepartment` AS select `I`.`name` AS `InstructorName`,`I`.`surname` AS `InstructorSurname`,`D`.`name` AS `DepartmentName`,`D`.`departmentID` AS `departmentID` from (`471db`.`instructor` `I` join `471db`.`department` `D` on((`I`.`departmentID` = `D`.`departmentID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`joinstudentdepartment` AS select `S`.`studentID` AS `studentID`,`S`.`name` AS `StudentName`,`S`.`surname` AS `StudentSurname`,`S`.`creditLimit` AS `creditLimit`,`S`.`startYear` AS `startYear`,`D`.`name` AS `DepartmentName`,`D`.`departmentID` AS `departmentID` from (`471db`.`student` `S` join `471db`.`department` `D` on((`S`.`departmentID` = `D`.`departmentID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`studentgradedcourse` AS select distinct `S`.`studentID` AS `studentID`,`S`.`name` AS `StudentName`,`S`.`surname` AS `StudentSurname`,`ccs`.`CourseName` AS `CourseName`,`SGC`.`grade` AS `grade` from ((`471db`.`student` `S` join `471db`.`joincourseclasssection` `CCS`) join `471db`.`studenthasgradedclass` `SGC`) where ((`S`.`studentID` = `SGC`.`studentID`) and (`ccs`.`classID` = `SGC`.`classID`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `471db`.`studenttakecourse` AS select `S`.`studentID` AS `studentID`,`S`.`name` AS `StudentName`,`S`.`surname` AS `StudentSurname`,`ccs`.`CourseName` AS `CourseName`,`ccs`.`credit` AS `credit` from ((`471db`.`student` `S` join `471db`.`joincourseclasssection` `CCS`) join `471db`.`studenttakencourse` `STC`) where ((`STC`.`studentID` = `S`.`studentID`) and (`STC`.`classID` = `ccs`.`classID`) and (`STC`.`sectionID` = `ccs`.`sectionID`));
